# Apps install dir
apps_install_dir = get_option('apps_install_dir')

################################################
# SUBDIRS
################################################


if get_option('build_case_studies')
    subdir('case_studies')
endif

if get_option('build_face_landmarks')
    subdir('face_landmarks')
endif

if get_option('build_lpr')
    subdir('license_plate_recognition')
endif

if get_option('build_clip')
    subdir('clip')
endif

if get_option('build_webserver')
    subdir('webserver')
endif

if get_option('build_native')
    
endif
