#pragma once

#define MEDIALIB_LOGGER_LEVEL_ENV_VAR ("MEDIALIB_LOG_LEVEL")
#define MEDIALIB_LOGGER_CONSOLE_ENV_VAR ("MEDIALIB_CONSOLE_LOG_LEVEL")
#define MEDIALIB_LOGGER_PATH_ENV_VAR ("MEDIALIB_LOGGER_PATH")
#define MEDIALIB_LOGGER_ROTATE_ENV_VAR ("MEDIALIB_LOGGER_ROTATE")
#define MEDIALIB_LOGGER_FILE_SIZE_ENV_VAR ("MEDIALIB_LOGGER_FILE_SIZE")

#define MEDIALIB_VSM_PRINT_ENV_VAR ("ENABLE_VSM_PRINTS")
#define MEDIALIB_GYRO_PRINT_ENV_VAR ("ENABLE_GYRO_PRINTS")

#define MEDIALIB_FD_DUP_ENV_VAR ("MEDIALIB_FD_DUP")

#define MEDIALIB_SNAPSHOT_ENABLE_ENV_VAR ("MEDIALIB_SNAPSHOT_ENABLE")
#define MEDIALIB_SNAPSHOT_PATH_ENV_VAR ("MEDIALIB_SNAPSHOT_PATH")
#define MEDIALIB_DEWARP_DSP_OPTIMIZATION_ENV_VAR ("MEDIALIB_DEWARP_DSP_OPTIMIZATION")
#define MEDIALIB_DEFAULT_TOTAL_COOLING_WAIT_TIME_IN_MINUTES_ENV_VAR ("DEFAULT_TOTAL_COOLING_WAIT_TIME_IN_MINUTES")
#define MEDIALIB_USE_DIV_FRAMERATE_LOGIC_ENV_VAR ("MEDIALIB_USE_DIV_FRAMERATE_LOGIC")
#define MEDIALIB_USE_AUTOMATIC_ALGORITHMS_WITH_RANGES ("MEDIALIB_USE_AUTOMATIC_ALGORITHMS_WITH_RANGES")
#define MEDIALIB_SKIP_METADATA_CONFIG_VALIDATION ("HAILO_MEDIA_LIB_SKIP_METADATA_CONFIG_VALIDATION")
#define MEDIALIB_ENCODER_FPS_UPDATE_INTERVAL_MS_ENV_VAR ("MEDIALIB_ENCODER_FPS_UPDATE_INTERVAL_MS")
#define MEDIALIB_SERVICE_GRPC_PORT_ENV_VAR ("MEDIALIB_SERVICE_GRPC_PORT")
#define MEDIALIB_SERVICE_BIND_ADDRESS_ENV_VAR ("MEDIALIB_SERVICE_BIND_ADDRESS")

// Service-related environment variables (gRPC server configuration and persistent config)
#define MEDIALIB_SERVICE_CONFIG_BACKUP_PATH_ENV_VAR ("MEDIALIB_SERVICE_CONFIG_BACKUP_PATH")
#define MEDIALIB_SERVICE_IGNORE_PERSISTENT_CONFIG_ENV_VAR ("MEDIALIB_SERVICE_IGNORE_PERSISTENT_CONFIG")
#define MEDIALIB_FRONTEND_PRINT_FPS_ENV_VAR ("MEDIALIB_FRONTEND_PRINT_FPS")
#define MEDIALIB_ENCODER_PRINT_FPS_ENV_VAR ("MEDIALIB_ENCODER_PRINT_FPS")
