# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import distutils.spawn
import os
import re
import sys


class NoReleaseVersionFound(Exception):
    pass


def _tex_escape(text: str):
    conversion_dict = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\^{}',
        '\\': r'\textbackslash{}',
        '<': r'\textless{}',
        '>': r'\textgreater{}',
    }
    sorted_keys = sorted(conversion_dict.keys(), key=(lambda item: -len(item)))
    regex = re.compile('|'.join(re.escape(key) for key in sorted_keys))
    return regex.sub(lambda match: conversion_dict[match.group()], text)


def _get_version():
    forced_release = os.getenv('DOC_VERSION')
    if forced_release:
        return forced_release

    raise NoReleaseVersionFound


# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = u'MediaLibrary'
copyright = u'2026, Hailo Technologies'
author = u'Hailo Technologies'
version = _get_version()
release = version
today_fmt = '%-d %B %Y'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'internal',
    'nbsphinx',
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.doctest',
    'sphinx.ext.mathjax',
    "sphinx.ext.intersphinx",
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
]

if distutils.spawn.find_executable('rsvg-convert'):
    extensions.append('sphinxcontrib.rsvgconverter')

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []
toc_filter_exclude = []
if not tags.has('internal'): # noqa: F821
    exclude_patterns.append('internal/*')
    toc_filter_exclude.append('internal/*')

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {}  # {'logo': 'logo.png'}

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
html_favicon = "_static/favicon.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# If true (and html_copy_source is true as well), links to the reST sources will be added to the sidebar. The default is True.
html_show_sourcelink = False

# Don't copy RST sources unless you're in internal mode, because they may contain confidential
# stuff
html_copy_source = tags.has('internal') # noqa: F821

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'MediaLibrarydoc'


# -- Options for LaTeX output ------------------------------------------------


latex_watermark_text = _tex_escape(os.getenv('WATERMARK', ''))
latex_watermark_preamble = ''
if latex_watermark_text:
    latex_watermark_preamble = r'''
            \usepackage{draftwatermark}
            \SetWatermarkText{''' + latex_watermark_text + r'''}
            \SetWatermarkScale{0.4}
            \SetWatermarkLightness{0.9}
    '''

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # 'preamble': '\\setcounter{tocdepth}{2}',

    # fonts stuff + truncate long signatures with "..."
    # this code is copied from sphinx.sty with some changes
    'preamble': r'''
        \usepackage{tabu}
        \addto\captionsenglish{\renewcommand{\contentsname}{Table of Contents}}
        \usepackage{tikz}
        \usepackage{adjustbox}
        \usepackage{tabularx}
        \usepackage{longtable}
        \usepackage{fontspec}
        \usepackage{graphicx}
        \usepackage{enumitem}
        \usepackage{titlesec}
        \usepackage{xstring}
        \usepackage{etoolbox}
        \usepackage[labelsep=period]{caption}
        \usepackage{geometry}
        \usepackage[normalem]{ulem} % For underlining
        \usepackage{hyperref}
        \definecolor{BlueForUrls}{rgb}{0.2588, 0.4588, 0.9137} % Example: light blue
        \definecolor{DeepCyan}{rgb}{0, 0.373, 0.557}
        \hypersetup{
            colorlinks=true,       % Enable colored links
            linkcolor=DeepCyan,        % Color for internal links
            citecolor=DeepCyan,        % Color for citations
            urlcolor=BlueForUrls,        % Color for URLs
            pdfborder={0 0 0}      % Disable borders around links
        }

        % Redefine URL font to include underline and color
        \renewcommand{\UrlFont}{\color{BlueForUrls}\uline} % Underline and color raw URLs

        % Redefine \href to ensure text links are underlined and colored
        \let\oldhref\href
        \renewcommand{\href}[2]{\textcolor{BlueForUrls}{\uline{\oldhref{#1}{#2}}}}

        % Redefine \url to ensure raw URLs are underlined and colored
        \let\oldurl\url
        \renewcommand{\url}[1]{\textcolor{BlueForUrls}{\uline{\oldurl{#1}}}}

        \setsansfont[Ligatures=TeX,Scale=MatchLowercase]{Open Sans}
        \setmonofont[Ligatures=TeX,Scale=MatchLowercase]{Courier}
        \setmainfont[Ligatures=TeX,Scale=MatchLowercase]{Open Sans}
        \usepackage{truncate}
        \definecolor{DarkAqua}{rgb}{0.000,0.596,0.769}
        \definecolor{NiceBlue}{rgb}{0.267,0.447,0.769}
        \definecolor{NiceDarkBlue}{rgb}{0.086,0.118,0.431}
        \makeatletter
        \ChNumVar{\LARGE\sffamily\bfseries} % sets the style for digit
        \ChTitleVar{\LARGE\sffamily\bfseries} % sets the style for title
        \ChRuleWidth{0pt}
        \patchcmd{\ttl@save@mkchap}{\vspace*{50\p@}}{}{}{}
        \patchcmd{\ttl@save@mkschap}{\vspace*{50\p@}}{\vspace*{10pt}}{}{}
        \patchcmd{\part}{plain}{mypart}{}{}
        \renewcommand{\DOCH}{\CNoV\textcolor{DeepCyan}{\thechapter .}\hspace{0.5em}}
        \renewcommand{\DOTI}[1]{\CTV\textcolor{DeepCyan}{#1}\\ \vspace{1em}}
        \renewcommand{\DOTIS}[1]{\CTV\textcolor{DeepCyan}{#1}}
        \titleformat{\section}{\Large\py@HeaderFamily}%
            {\py@TitleColor\thesection .}{0.5em}{\py@TitleColor}{\py@NormalColor}
        \titleformat{\subsection}{\large\py@HeaderFamily}%
            {\py@TitleColor\thesubsection .}{0.5em}{\py@TitleColor}{\py@NormalColor}
        \titleformat{\subsubsection}{\py@HeaderFamily}%
            {\py@TitleColor\thesubsubsection .}{0.5em}{\py@TitleColor}{\py@NormalColor}

        \AtBeginEnvironment{tabulary}{
            \setlist[itemize,1]{nosep, wide=0pt, leftmargin=*, before=\vspace*{-0.5\baselineskip}, after=\vspace*{\dimexpr1ex-\baselineskip-0.5em}}
            \setlist[itemize,2]{leftmargin=*}
        }
        \AtBeginEnvironment{fulllineitems}{
            % Remove space around headings inside function/struct API doc
            \titlespacing*{\subsubsection}{0em}{0em}{0em}
        }
        \newcommand{\titletext}[1]{\sffamily\textcolor{TitleColor}{#1}}
        \newcommand{\headerfootertext}[1]{\sffamily\textcolor{black}{#1}}
        \renewcommand{\py@sigparams}[2]{%
            \parbox[t]{\py@argswidth}{\truncate[ ...\sphinxcode{)}]{\py@argswidth}{#1\sphinxcode{)}#2}}}
        \renewcommand{\headrule}{\vspace{-0.7em}\vbox to 0pt{\hbox to\headwidth{%
            \color{black}\leaders\hrule height \headrulewidth\hfill}}}
        \renewcommand{\footrule}{\hbox to\headwidth{%
            \color{black}\leaders\hrule height \footrulewidth\hfill}}
        \fancypagestyle{mytitle}{
            \renewcommand{\headrulewidth}{0pt}
            \renewcommand{\footrulewidth}{0pt}
            \addtolength{\footskip}{0.8em}
            \fancyfoot[CO]{{\vspace{0.8em}\titletext{\large Confidential and Proprietary. Unauthorized Reproduction Prohibited}}}
            \fancyfoot[LO,RO]{{}}
            \fancyhead{{}}
        }
        \fancypagestyle{normal}{
            \fancyhf{}
            % FIXME: this presupposes "twoside".
            % If "oneside" class option, there are warnings in LaTeX log.
            \fancyfoot[CE,CO]{{\headerfootertext{Page \thepage\qquad\py@release\qquad Confidential and Proprietary | Copyright \textcopyright \ 2026 -- Hailo Technologies Ltd.}}}
            \fancyhead[LE,LO]{{\includegraphics[width=3.5cm]{logo_small.pdf}\hspace{8.0cm}\headerfootertext{\@title}}}
            \renewcommand{\headrulewidth}{0.4pt}
            \renewcommand{\footrulewidth}{0.4pt}
            % define chaptermark with \@chappos when \@chappos is available for Japanese
            \ltx@ifundefined{@chappos}{}
            {\def\chaptermark##1{\markboth{\@chapapp\space\thechapter\space\@chappos\space ##1}{}}}
        }
        \fancypagestyle{plain}{
            \fancyhf{}
            \fancyfoot[CE,CO]{{\headerfootertext{Page \thepage\qquad\py@release\qquad Confidential and Proprietary | Copyright \textcopyright \ 2026 -- Hailo Technologies Ltd.}}}
            \fancyhead[LE,LO]{{\includegraphics[width=3.5cm]{logo_small.pdf}\hspace{8.0cm}\headerfootertext{\@title}}}
            \renewcommand{\headrulewidth}{0.4pt}
            \renewcommand{\footrulewidth}{0.4pt}
        }
        \fancypagestyle{mypart}{
            \fancyhf{}
            \fancyfoot[CE,CO]{{\headerfootertext{Page \thepage\qquad\py@release\qquad Confidential and Proprietary | Copyright \textcopyright \ 2026 -- Hailo Technologies Ltd.}}}
            \fancyhead[LE,LO]{}
            \renewcommand{\headrulewidth}{0pt}
            \renewcommand{\footrulewidth}{0.4pt}
        }

        \makeatother
        \pagestyle{normal} % See: https://tex.stackexchange.com/questions/407929/thispagestyle-and-pagestyle-with-packages-fancyhdr-and-extramarks-causes-confu
        \taburulecolor{gray!30}
        \def\arraystretch{1.3}
    ''' + latex_watermark_preamble,

    'maketitle': r'''
        \newgeometry{left=1.9cm,right=1.9cm,top=2cm,bottom=0cm}
        \makeatletter
        \let\sphinxrestorepageanchorsetting\relax
        \ifHy@pageanchor\def\sphinxrestorepageanchorsetting{\Hy@pageanchortrue}\fi
        \hypersetup{pageanchor=false}% avoid duplicate destination warnings
        \begin{titlepage}%
            \thispagestyle{mytitle}
            \tikz[remember picture,overlay] \node[inner sep=0pt] at (current page.center){\includegraphics{Hailo_dots.pdf}};
            \let\footnotesize\small
            \let\footnoterule\relax
            \begingroup % for PDF information dictionary
                \def\endgraf{ }\def\and{\& }%
                \pdfstringdefDisableCommands{\def\\{, }}% overwrite hyperref setup
                \hypersetup{pdfauthor={\@author}, pdftitle={\@title}}%
            \endgroup
            \sphinxlogo
            \vfill\vfill
            {\fontsize{28}{10}\selectfont\setmainfont{Open Sans}\textbf{\@title} \par}
            \vspace{0.5cm}
            {\colorbox[rgb]{0.24,0.60,0.78}{\makebox[0.66cm]{\rule{0pt}{0.01cm}}} \par}
            \vspace{0.5cm}
            {\fontsize{12}{3}\selectfont\setmainfont{Open Sans}{\py@release\releaseinfo} \par}
            {\fontsize{12}{3}\selectfont\setmainfont{Open Sans}\textcolor{black}{\@date} \par}
            \vfill\vfill\vfill\vfill
            \@thanks
        \end{titlepage}%
        \setcounter{footnote}{0}%
        \let\thanks\relax\let\maketitle\relax
        %\gdef\@thanks{}\gdef\@author{}\gdef\@title{}
        \clearpage
        \ifdefined\sphinxbackoftitlepage\sphinxbackoftitlepage\fi
        \if@openright\cleardoublepage\else\clearpage\fi
        \sphinxrestorepageanchorsetting
        \makeatother
        \restoregeometry
    ''',

    # Latex figure (float) alignment
    # 'figure_align': 'h',

    # Don't include the index (it looks ugly in the PDF)
    'printindex': '',

    'fncychap': '\\usepackage{fncychap}',

    'sphinxsetup': """InnerLinkColor={rgb}{0, 0.373, 0.557},
                      TitleColor={rgb}{0, 0.373, 0.557},
                      VerbatimColor={rgb}{0.866,0.933,0.933},
                      noteBorderColor={rgb}{0.415,0.690,0.870},
                      warningBorderColor={rgb}{0.941,0.701,0.494},
                      warningBgColor={rgb}{1,0.929,0.8},
                      VerbatimBorderColor={rgb}{0.882,0.894,0.898},
                      OuterLinkColor={rgb}{0.2588, 0.4588, 0.9137}""",

    'extraclassoptions': 'openany',

    'passoptionstopackages': r'\PassOptionsToPackage{table}{xcolor}',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, f'hailo_media_library_{release}_user_guide.tex', u'Hailo Media Library User Guide',
     u'Hailo Technologies', 'manual'),
]

latex_logo = '_images_src/Hailo_logo_for_A4.pdf'

latex_engine = 'xelatex'


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'media_library', u'MediaLibrary Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'MediaLibrary', u'MediaLibrary Documentation',
     author, 'MediaLibrary', 'Hailo Media Library',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Custom stuff ------------------------------------------------------------

# Don't ignore __init__ doc

def skip(app, what, name, obj, skip, options):
    if name == '__init__':
        return False
    return skip


def setup(app):
    app.connect('autodoc-skip-member', skip)
    app.add_css_file('css/custom.css')


# Sort the classes and functions in the autogenerated HTML according to the source files order
# (as opposed to alphabetically)
autodoc_member_order = 'bysource'

# Ignore __all__ so modules such as ClientRunner won't appear twice in the doc
autodoc_default_options = {
    'ignore-module-all': True
}

# Breathe (C++ doc stuff)
# breathe_projects is overridden by the Makefile
breathe_projects = {'media_library': None}
breathe_default_project = 'media_library'
cpp_id_attributes = ['HAILORTAPI']

# Numfig
# numfig is overridden by the Makefile to set it only in Latex, to fix some numbering issues there
numfig = False
numfig_format = {'figure': 'Figure %s'}
numfig_secnum_depth = 0

# Disabling notebook running while compiling it
nbsphinx_execute = 'never'


# -- Options for media library custom settings ----------------------------------------------
breathe_show_define_initializer = True
