#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <thread>
#include <chrono>
#include <vector>
#include <atomic>
#include <memory>
#include <iostream>
#include <fstream>
#include <map>

#include "hailo_analytics/pipeline/core/pipeline.hpp"
#include "hailo_analytics/pipeline/sources/frontend_stage.hpp"
#include "core_tests/core_tests_common.hpp"
#include "media_library/media_library.hpp"
#include "media_library/frontend.hpp"
#include "media_library/media_library_types.hpp"
#include "media_library/examples_common.hpp"

using namespace hailo_analytics::pipeline;
using namespace hailo_analytics::pipeline::sources;
using ::testing::_;
using ::testing::Return;

// ============================================================================
// Test Helper - Creates MediaLibrary with Frontend for testing
// ============================================================================

// Helper to create a MediaLibrary instance with a valid frontend configuration.
// This uses the full MediaLibrary initialization to properly set up the frontend.
//
// BUFFER FLOW TESTING APPROACH:
// ==============================
// Unlike typical unit tests that mock dependencies, these tests use REAL buffer flow
// from the MediaLibraryFrontend because:
//
// 1. The frontend produces buffers autonomously from its GStreamer pipeline
// 2. Buffers are generated by the configured input source at a steady FPS
// 3. There's no external API to "inject" or "simulate" buffers
// 4. The callback mechanism is internal to GStreamer elements
//
// Therefore, to test buffer forwarding:
// - We use the real MediaLibrary with actual configuration files
// - We start the pipeline (which activates the input source)
// - We wait for real buffers to be produced and flow through
// - We use TestThreadedStage subscribers (which process buffers in their own threads)
// - We verify that buffers were received (without checking exact counts)
//
// This makes these tests more integration-style, but it's the only way to properly
// test the FrontendStage's buffer forwarding functionality with the real frontend.
class MediaLibraryTestHelper
{
  public:
    MediaLibraryPtr media_lib;
    std::atomic<int> subscribe_call_count{0};
    std::atomic<int> start_call_count{0};
    std::atomic<int> stop_call_count{0};
    FrontendCallbacksMap stored_callbacks;
    std::mutex callbacks_mutex;

    // Create a MediaLibrary instance with frontend configured
    // Uses the test configuration from the examples directory
    static std::shared_ptr<MediaLibraryTestHelper> create()
    {
        auto helper = std::make_shared<MediaLibraryTestHelper>();

        // Create MediaLibrary
        auto media_lib_result = MediaLibrary::create();
        if (!media_lib_result.has_value())
        {
            throw std::runtime_error("Failed to create MediaLibrary for testing");
        }

        helper->media_lib = media_lib_result.value();

        // Try to load configuration from examples directory
        // If not available, skip the test
        std::ifstream config_file(config_path);
        if (!config_file.good())
        {
            throw std::runtime_error("Frontend test configuration file not found (" + config_path +
                                     "). Tests require media library configuration.");
        }

        std::string config_string((std::istreambuf_iterator<char>(config_file)), std::istreambuf_iterator<char>());
        config_file.close();

        // Initialize the media library with the configuration
        auto init_status = helper->media_lib->initialize(config_string);
        if (init_status != MEDIA_LIBRARY_SUCCESS)
        {
            throw std::runtime_error("Failed to initialize MediaLibrary with configuration");
        }

        return helper;
    }

    MediaLibraryFrontendPtr get_frontend()
    {
        return media_lib->m_frontend;
    }

    // Track subscribe calls by wrapping the frontend's subscribe method
    media_library_return subscribe_to_frontend(FrontendCallbacksMap callbacks)
    {
        subscribe_call_count++;
        {
            std::lock_guard<std::mutex> lock(callbacks_mutex);
            stored_callbacks = callbacks;
        }
        return media_lib->subscribe_to_frontend_output(callbacks);
    }

    // Track start/stop through the media library
    media_library_return start_pipeline()
    {
        start_call_count++;
        return media_lib->start_pipeline();
    }

    media_library_return stop_pipeline()
    {
        stop_call_count++;
        return media_lib->stop_pipeline();
    }

    ~MediaLibraryTestHelper()
    {
        if (media_lib)
        {
            media_lib->stop_pipeline();
        }
    }
};
// ============================================================================
// FrontendStage Test Fixture
// ============================================================================

class FrontendStageTest : public ::testing::Test
{
  protected:
    std::shared_ptr<MediaLibraryTestHelper> media_lib_helper;
    HailoMediaLibraryBufferPtr mock_buffer;

    void SetUp() override
    {
        try
        {
            media_lib_helper = MediaLibraryTestHelper::create();
            mock_buffer = std::make_shared<hailo_media_library_buffer>();
        }
        catch (const std::exception &e)
        {
            GTEST_SKIP() << "Failed to create MediaLibrary for frontend testing: " << e.what()
                         << "\nNote: FrontendStage tests require valid media library configuration files.";
        }
    }

    void TearDown() override
    {
        if (media_lib_helper)
        {
            media_lib_helper->stop_pipeline();
        }
        media_lib_helper.reset();
        mock_buffer.reset();
    }

    BufferPtr create_test_buffer()
    {
        return std::make_shared<Buffer>(mock_buffer);
    }

    MediaLibraryFrontendPtr get_frontend()
    {
        return media_lib_helper->get_frontend();
    }
};

// ============================================================================
// Test Cases
// ============================================================================

// Test FrontendStage construction
TEST_F(FrontendStageTest, ConstructorCreatesValidStage)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend", 5, false, true);
    ASSERT_NE(stage, nullptr);
}

// Test Builder pattern
TEST_F(FrontendStageTest, BuilderCreatesStageWithCorrectName)
{
    auto stage = FrontendStageBuild::create()
                     .set_stage_name("test_frontend_builder")
                     .set_queue_size_opt(10)
                     .set_leaky_opt(true)
                     .set_trace_opt(true)
                     .buildptr();

    ASSERT_NE(stage, nullptr);
}

TEST_F(FrontendStageTest, BuilderThrowsWhenNameNotSet)
{
    EXPECT_THROW({ auto stage = FrontendStageBuild::create().set_queue_size_opt(10).buildptr(); }, std::runtime_error);
}

// Test configure method
TEST_F(FrontendStageTest, ConfigureSucceedsWithValidFrontend)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    auto status = stage->configure(get_frontend());
    EXPECT_EQ(status, AppStatus::SUCCESS);
    // Frontend should be configured - verify by checking we can get streams
    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value());
}

TEST_F(FrontendStageTest, ConfigureSubscribesToAllOutputStreams)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    auto status = stage->configure(get_frontend());
    EXPECT_EQ(status, AppStatus::SUCCESS);

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value());
    // Configuration from medialib_config.json should have at least one stream
    EXPECT_GT(streams.value().size(), 0);
}

// Test create method
TEST_F(FrontendStageTest, CreateSubscribesToFrontend)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    auto status = stage->create(get_frontend());
    EXPECT_EQ(status, AppStatus::SUCCESS);
    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value());
}

// Test subscribe_to_stream
TEST_F(FrontendStageTest, SubscribeToStreamSucceedsWithValidStreamId)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    auto subscriber = std::make_shared<SimpleStage>("subscriber_1");
    auto status = stage->subscribe_to_stream(stream_id, subscriber);

    EXPECT_EQ(status, AppStatus::SUCCESS);
    EXPECT_EQ(subscriber->queue_names.size(), 1);
    EXPECT_EQ(subscriber->queue_names[0], stream_id);
}

TEST_F(FrontendStageTest, SubscribeToStreamFailsWithInvalidStreamId)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto subscriber = std::make_shared<SimpleStage>("subscriber_1");
    auto status = stage->subscribe_to_stream("invalid_stream_that_does_not_exist", subscriber);

    EXPECT_EQ(status, AppStatus::INVALID_ARGUMENT);
}

TEST_F(FrontendStageTest, SubscribeToStreamFailsWhenFrontendNotConfigured)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    auto subscriber = std::make_shared<SimpleStage>("subscriber_1");

    auto status = stage->subscribe_to_stream("any_stream", subscriber);
    EXPECT_EQ(status, AppStatus::UNINITIALIZED);
}

TEST_F(FrontendStageTest, MultipleSubscribersCanSubscribeToSameStream)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    auto subscriber1 = std::make_shared<SimpleStage>("subscriber_1");
    auto subscriber2 = std::make_shared<SimpleStage>("subscriber_2");

    stage->subscribe_to_stream(stream_id, subscriber1);
    stage->subscribe_to_stream(stream_id, subscriber2);

    EXPECT_EQ(subscriber1->queue_names.size(), 1);
    EXPECT_EQ(subscriber2->queue_names.size(), 1);
}

TEST_F(FrontendStageTest, SubscriberCanSubscribeToMultipleStreams)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && streams.value().size() >= 2);
    auto stream_id1 = streams.value()[0].id;
    auto stream_id2 = streams.value()[1].id;

    auto subscriber = std::make_shared<SimpleStage>("subscriber_1");

    stage->subscribe_to_stream(stream_id1, subscriber);
    stage->subscribe_to_stream(stream_id2, subscriber);

    EXPECT_EQ(subscriber->queue_names.size(), 2);
    EXPECT_EQ(subscriber->queue_names[0], stream_id1);
    EXPECT_EQ(subscriber->queue_names[1], stream_id2);
}

// ============================================================================
// Buffer Forwarding Tests
// ============================================================================
// These tests verify that buffers actually flow from the frontend through the
// FrontendStage to subscribers. They start the real pipeline and wait for
// actual buffers to be produced by the frontend's input source.
// ============================================================================

TEST_F(FrontendStageTest, BuffersForwardedToSubscriber)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    // Get first available stream ID from configuration
    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    // Use TestThreadedStage which can accept buffers in its own thread
    auto subscriber = std::make_shared<TestThreadedStage>("subscriber_1", 10);
    stage->subscribe_to_stream(stream_id, subscriber);

    // Start the stage (which starts the frontend and begins producing buffers)
    stage->start();
    subscriber->start();

    // Wait for the frontend to produce and forward some buffers
    // The frontend will autonomously produce buffers from its input source
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Stop stages
    stage->stop();
    subscriber->stop();

    // Verify that buffers were received
    // We don't check exact count since it depends on framerate and timing,
    // just that some buffers flowed through
    auto processed = subscriber->get_process_call_count();
    EXPECT_GT(processed, 0) << "Subscriber should have received buffers from frontend";
}

TEST_F(FrontendStageTest, BuffersForwardedToMultipleSubscribers)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    // Create multiple subscribers using TestThreadedStage
    auto subscriber1 = std::make_shared<TestThreadedStage>("subscriber_1", 10);
    auto subscriber2 = std::make_shared<TestThreadedStage>("subscriber_2", 10);

    stage->subscribe_to_stream(stream_id, subscriber1);
    stage->subscribe_to_stream(stream_id, subscriber2);

    // Start the pipeline
    stage->start();
    subscriber1->start();
    subscriber2->start();

    // Wait for buffers to flow
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Stop stages
    stage->stop();
    subscriber1->stop();
    subscriber2->stop();

    // Verify both subscribers received buffers
    auto processed1 = subscriber1->get_process_call_count();
    auto processed2 = subscriber2->get_process_call_count();

    EXPECT_GT(processed1, 0) << "First subscriber should have received buffers";
    EXPECT_GT(processed2, 0) << "Second subscriber should have received buffers";
}

TEST_F(FrontendStageTest, BuffersForwardedToCorrectStreamSubscribers)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && streams.value().size() >= 2);
    auto stream_id1 = streams.value()[0].id;
    auto stream_id2 = streams.value()[1].id;

    // Create subscribers for different streams
    auto subscriber1 = std::make_shared<TestThreadedStage>("subscriber_1", 10);
    auto subscriber2 = std::make_shared<TestThreadedStage>("subscriber_2", 10);

    stage->subscribe_to_stream(stream_id1, subscriber1);
    stage->subscribe_to_stream(stream_id2, subscriber2);

    // Start the pipeline
    stage->start();
    subscriber1->start();
    subscriber2->start();

    // Wait for buffers to flow
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Stop stages
    stage->stop();
    subscriber1->stop();
    subscriber2->stop();

    // Verify both subscribers received buffers from their respective streams
    auto processed1 = subscriber1->get_process_call_count();
    auto processed2 = subscriber2->get_process_call_count();

    EXPECT_GT(processed1, 0) << "Subscriber on " << stream_id1 << " should have received buffers";
    EXPECT_GT(processed2, 0) << "Subscriber on " << stream_id2 << " should have received buffers";
}

// Test init and deinit
TEST_F(FrontendStageTest, InitStartsFrontend)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto status = stage->init();
    EXPECT_EQ(status, AppStatus::SUCCESS);
    // Frontend should be started - verify by checking it can be used
}

TEST_F(FrontendStageTest, InitFailsWhenFrontendNotConfigured)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    auto status = stage->init();
    EXPECT_EQ(status, AppStatus::UNINITIALIZED);
}

TEST_F(FrontendStageTest, DeinitStopsFrontend)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());
    stage->init();

    auto status = stage->deinit();
    EXPECT_EQ(status, AppStatus::SUCCESS);
    // Frontend should be stopped
}

// Test lifecycle
TEST_F(FrontendStageTest, StartStopLifecycle)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    auto subscriber = std::make_shared<TestThreadedStage>("subscriber_1", 10);
    stage->subscribe_to_stream(stream_id, subscriber);

    // Start the stage and subscriber
    subscriber->start();
    stage->start();

    // Wait longer for the frontend pipeline to fully initialize and produce buffers
    // Frontend needs time to start GStreamer pipeline and begin streaming
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Stop the stage
    stage->stop();
    subscriber->stop();

    // Verify buffers were received during the lifecycle
    auto processed = subscriber->get_process_call_count();
    EXPECT_GT(processed, 0) << "Buffers should flow during stage lifecycle";
}

TEST_F(FrontendStageTest, DestructorUnsubscribesAll)
{
    // auto local_helper = MediaLibraryTestHelper::create();
    {
        auto stage = std::make_shared<FrontendStage>("test_frontend");
        stage->configure(get_frontend());
    } // stage goes out of scope

    // Destructor should call unsubscribe_all - frontend should still be functional
    auto streams = get_frontend()->get_outputs_streams();
    EXPECT_TRUE(streams.has_value());
}

// Test that stage can be stopped and restarted
TEST_F(FrontendStageTest, StageCanBeStoppedAndRestarted)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    auto subscriber = std::make_shared<TestThreadedStage>("subscriber_1", 10);
    stage->subscribe_to_stream(stream_id, subscriber);

    // First run
    subscriber->start();
    stage->start();
    std::this_thread::sleep_for(std::chrono::seconds(1));
    stage->stop();
    subscriber->stop();
    std::this_thread::sleep_for(std::chrono::seconds(1));

    auto first_count = subscriber->get_process_call_count();
    EXPECT_GT(first_count, 0) << "Should receive buffers in first run";

    // Second run - restart the same stage
    subscriber->start();
    stage->start();
    std::this_thread::sleep_for(std::chrono::seconds(1));
    stage->stop();
    subscriber->stop();
    std::this_thread::sleep_for(std::chrono::seconds(1));

    auto second_count = subscriber->get_process_call_count();
    EXPECT_GT(second_count, first_count) << "Should receive more buffers after restart";
}

// Test get_outputs_streams
TEST_F(FrontendStageTest, GetOutputStreamsReturnsCorrectStreams)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value());
    EXPECT_GT(streams.value().size(), 0);

    // Verify stream properties are populated
    for (const auto &stream : streams.value())
    {
        EXPECT_FALSE(stream.id.empty());
        EXPECT_GT(stream.width, 0);
        EXPECT_GT(stream.height, 0);
    }
}

// Test continuous buffer flow
TEST_F(FrontendStageTest, ContinuousBufferFlowFromFrontend)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    auto subscriber = std::make_shared<TestThreadedStage>("subscriber_1", 20);
    stage->subscribe_to_stream(stream_id, subscriber);

    // Start the pipeline
    stage->start();
    subscriber->start();

    // Let the frontend produce buffers continuously
    // At typical framerates (30fps), we should get multiple buffers
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Stop and check
    stage->stop();
    subscriber->stop();

    auto processed = subscriber->get_process_call_count();

    // Verify we received multiple buffers (not just one)
    // This confirms the frontend is continuously producing frames
    EXPECT_GT(processed, 5) << "Should receive multiple buffers over 2 seconds";
}

// Test builder with all options
TEST_F(FrontendStageTest, BuilderWithAllOptions)
{
    auto stage = FrontendStageBuild::create()
                     .set_stage_name("full_config_frontend")
                     .set_queue_size_opt(20)
                     .set_leaky_opt(true)
                     .set_trace_opt(true)
                     .buildptr();

    ASSERT_NE(stage, nullptr);

    // Configure and verify it works
    auto status = stage->configure(get_frontend());
    EXPECT_EQ(status, AppStatus::SUCCESS);
}

// Test thread safety with multiple subscribers receiving buffers concurrently
TEST_F(FrontendStageTest, ThreadSafetyWithMultipleConcurrentSubscribers)
{
    auto stage = std::make_shared<FrontendStage>("test_frontend");
    stage->configure(get_frontend());

    auto streams = stage->get_outputs_streams();
    ASSERT_TRUE(streams.has_value() && !streams.value().empty());
    auto stream_id = streams.value()[0].id;

    // Create multiple subscribers that will all receive buffers concurrently
    std::vector<std::shared_ptr<TestThreadedStage>> subscribers;
    const int num_subscribers = 5;

    for (int i = 0; i < num_subscribers; i++)
    {
        auto sub = std::make_shared<TestThreadedStage>("subscriber_" + std::to_string(i), 10);
        subscribers.push_back(sub);
        stage->subscribe_to_stream(stream_id, sub);
    }

    // Start all subscribers and the stage
    stage->start();
    for (auto &sub : subscribers)
    {
        sub->start();
    }

    // Let buffers flow to all subscribers concurrently
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Stop all
    stage->stop();
    for (auto &sub : subscribers)
    {
        sub->stop();
    }

    // Verify all subscribers received buffers safely without crashes
    for (size_t i = 0; i < subscribers.size(); i++)
    {
        auto processed = subscribers[i]->get_process_call_count();
        EXPECT_GT(processed, 0) << "Subscriber " << i << " should have received buffers";
    }
}

// Test that stage name is properly set
TEST_F(FrontendStageTest, StageNameIsCorrect)
{
    std::string expected_name = "my_frontend_stage";
    auto stage = FrontendStageBuild::create().set_stage_name(expected_name).buildptr();

    ASSERT_NE(stage, nullptr);
    // Note: Stage base class should have a way to get the name
    // This assumes the name is accessible somehow in the implementation
}
