#pragma once

#define MEDIALIB_LOGGER_LEVEL_ENV_VAR ("MEDIALIB_LOG_LEVEL")
#define MEDIALIB_LOGGER_CONSOLE_ENV_VAR ("MEDIALIB_CONSOLE_LOG_LEVEL")
#define MEDIALIB_LOGGER_PATH_ENV_VAR ("MEDIALIB_LOGGER_PATH")
#define MEDIALIB_LOGGER_ROTATE_ENV_VAR ("MEDIALIB_LOGGER_ROTATE")
#define MEDIALIB_LOGGER_FILE_SIZE_ENV_VAR ("MEDIALIB_LOGGER_FILE_SIZE")

#define MEDIALIB_FD_DUP_ENV_VAR ("MEDIALIB_FD_DUP")
#define MEDIALIB_DEWARP_DSP_OPTIMIZATION_ENV_VAR ("MEDIALIB_DEWARP_DSP_OPTIMIZATION")
