#pragma once

#include <optional>
#include <string>
#include <unordered_set>
#include <functional>
#include "hailo_analytics/pipeline/core/pipeline_builder.hpp"
#include "hailo_analytics/pipeline/overlay/overlay_stage.hpp"
#include "hailo_analytics/analytics/vision.hpp"
#include "hailo_postprocess_tools/objects/hailo_objects.hpp"
#include "tl/expected.hpp"

namespace hailo_analytics::analytics::overlay
{

namespace overlay_stage = hailo_analytics::pipeline::overlay;

/**
 * @brief Configuration structure for overlay stages.
 *
 * Contains all configurable parameters for OverlayStage builders.
 * All parameters are optional to allow flexible configuration.
 */
struct overlay_config_t
{
    std::optional<std::string> stage_name;
    std::optional<bool> skip;
    std::optional<bool> partial_landmarks;
    std::optional<std::unordered_set<size_t>> landmark_indices_to_draw;
    std::optional<size_t> queue_size;
    std::optional<bool> leaky;
    std::optional<std::unordered_set<int>> class_ids_to_draw;
    std::optional<std::function<cv::Scalar(const HailoDetectionPtr &)>> color_selector;
    std::optional<bool> trace;

    /**
     * @brief Merge configuration from another overlay_config_t.
     * Non-empty optional values from 'other' will override this config's values.
     *
     * @param other The configuration to merge from
     */
    void merge_from(const overlay_config_t &other);

    /**
     * @brief Apply this configuration to an OverlayStageBuild::Builder.
     * Only non-empty optional values will be applied.
     *
     * @param b The builder to configure
     */
    void apply_to(overlay_stage::OverlayStageBuild::Builder &b) const;
};

/**
 * @brief Combined configuration for overlay and vision output pipeline.
 *
 * This structure combines overlay configuration with vision output configuration
 * for a complete overlay + encoder + UDP pipeline.
 */
struct overlay_vision_output_config_t
{
    overlay_config_t overlay_config;
    vision::vision_output_config_t vision_output_config;

    /**
     * @brief Merge configuration from another overlay_vision_output_config_t.
     *
     * @param other The configuration to merge from
     */
    void merge_from(const overlay_vision_output_config_t &other);

    /**
     * @brief Apply overlay configuration to a builder.
     *
     * @param b The builder to configure
     */
    void apply_to(overlay_stage::OverlayStageBuild::Builder &b) const;
};

/**
 * @brief Get default configuration for overlay stage.
 *
 * @return overlay_config_t with sensible defaults
 */
overlay_config_t base_overlay_config();

/**
 * @brief Get default configuration for overlay vision output pipeline.
 *
 * Returns an overlay_vision_output_config_t with default overlay and vision output configurations.
 *
 * @param output_stream_id The output stream ID for the vision output
 * @return overlay_vision_output_config_t with sensible defaults
 */
overlay_vision_output_config_t base_overlay_vision_output_config(std::string output_stream_id = "sink0");

/**
 * @brief Generate an overlay pipeline with vision output.
 *
 * Creates a pipeline with an overlay stage as the first stage, followed by
 * a vision output pipeline (encoder -> UDP) generated by generate_vision_output_pipeline().
 *
 * @param media_library Shared pointer to the MediaLibrary instance
 * @param stream_id The output stream ID for the encoder
 * @param pipeline_name Name for the generated pipeline
 * @param user_configs Optional user-provided configuration (will be merged with defaults if provided)
 * @return Expected<PipelinePtr, AppStatus> The constructed overlay pipeline or error status
 */
tl::expected<hailo_analytics::pipeline::PipelinePtr, hailo_analytics::pipeline::AppStatus> generate_overlay_pipeline(
    MediaLibraryInterfacePtr media_library, const output_stream_id_t &stream_id,
    const std::string &pipeline_name = "overlay_pipeline",
    std::optional<overlay_vision_output_config_t> user_configs = std::nullopt);

} // namespace hailo_analytics::analytics::overlay
